# Generated by Django 3.1.1 on 2020-09-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200907_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualenterprisesurvey2019financialyearprovisionalcsv',
            options={'managed': False},
        ),
    ]
