# Generated by Django 3.1.1 on 2020-09-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_datate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollsData',
        ),
    ]
